
version: "3.9"
services:
  db:
    image: postgres:16
    container_name: rls_demo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rlsdemo
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rlsdemo"]
      interval: 3s
      timeout: 5s
      retries: 10
