name: Auto-Grade Homework

on:
  push:
    branches:
      - '**'   # all branches

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Code checked out!"
      
      - name: Set up Node
        uses: actions/setup-node@v4
      - run: echo "Node set up!"
      
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          
      - name: Run grading script
        run: |
          echo "Checking homework 2..."
          node test-problems.js hw2
        
      - run: echo "Grading Complete!"
